name: sane_workspace

packages:
  - packages/**

scripts:
  format-check:
    run: melos exec dart format . --set-exit-if-changed
    description: "Run dart format in all packages"
  test:
    run: melos exec dart test .
    description: "Run dart test in all packages"
